pipeline:
  identifier: Build_mhennycbm_my_react_workspace_1771434823124
  name: Build my-react-workspace
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1771434812137
        repoName: mhennycbm/my-react-workspace
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
